on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "Test code and check lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Install uv"
        uses: astral-sh/setup-uv@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: "Install dev dependencies"
        run: make install
      - name: "Run linters"
        run: make lint
      - name: "Run tests"
        run: make test
