on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "Test code and check lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: "Python Poetry Action"
        uses: Gr1N/setup-poetry@v8
      - name: "Install dev dependencies"
        run: make install
      - name: "Run linters"
        run: make lint
      - name: "Run tests"
        run: make test
